spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
  data:
    mongodb:
      #uri:  mongodb://localhost:27017/elderly
      host: localhost
      database: elderly
      port: 27017
      username: root
      password: "root"
      authentication-database: admin
      auto-index-creation: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      USE_GETTERS_AS_SETTERS: true
    parser:
      ALLOW_SINGLE_QUOTES: true
server:
  port: 9999